baseURL = "https://alannguyen.dev/"
languageCode = "en-us"
title = "</alan nguyen>"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-145579470-1"

datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    theme_color = "tomato"
    description = "Website of Alan Nguyen"
    favicon = "favicon.png"
    logo = "logo.png"
    email = "iam@alannguyen.dev"
    linkedin = "https://www.linkedin.com/in/anguyen120/"
    github = "anguyen120"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar.jpg"
    subtitle = "Howdy! I am Alan, a student from Texas."
    hero_right = ["**I am currently a senior at Texas A&M University pursuing a Bachelor's degree in Computing.**", "After my first semester of college, I spent 10 weeks as an intern at Oak Ridge National Laboratory (ORNL). During my internship, I volunteered for an event called "Introduce Your Daughter to Code" hosted at ORNL. Suzanne, a computational astrophysicist, kicked off the occasion with an introduction to Titan, ORNL's flagship supercomputer. One of the girls asked Suzanne how one would be able to work alongside a supercomputer. She responded that she believes one should continue to foster curiosity and passion for science and technology, as the future generation will build on their predecessors. Currently, Summit replaced and outperformed Titan. Summit will build on Titan's legacy.",  "After being an intern at ORNL, I attended J.P. Morgan’s hackathon, Code for Good 2017, where I worked with SEARCH Homeless Services and innovate their website. I realized how amazing I could use computing to help others! These experiences led me to serve as an officer for Aggie Web Developers, where we support our members' professional development by providing opportunities to learn about diversity, ethical business models, and the importance of mental health. I believe I am contributing to the advancement of technology. I want to continue my contribution and create my legacy by helping people through software and web development!", "I am interested in an internship for summer 2021. Please don't hesitate to contact me. 👍"] 
    resume = "Alan_Nguyen_Resume.pdf"

[params.process]
    enable = true
    title = "My Work"

[params.footer]
    enable = true
