baseURL = "https://alannguyen.dev/"
languageCode = "en-us"
title = "</alan nguyen>"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-145579470-1"

datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    theme_color = "tomato"
    description = "Website of Alan Nguyen"
    favicon = "favicon.png"
    logo = "logo.png"
    email = "iam@alannguyen.dev"
    linkedin = "https://www.linkedin.com/in/anguyen120/"
    github = "anguyen120"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar.jpg"
    subtitle = "Howdy! I am Alan, a student from Texas."
    hero_right = ["**I am currently a senior at Texas A&M University pursuing a Bachelor’s degree in Computing and expected to graduate in December 2021.**", "I attended J.P. Morgan’s hackathon, Code for Good 2017, and I worked with SEARCH Homeless Services and innovate their website. I realized how amazing I could use computing to help others! These experiences led me to serve as an officer for Aggie Web Developers, where we are also supporting our member’s professional development to learn about diversity, ethical business models, and the importance of mental health besides web development skills. I want to continue my contribution and create my legacy by helping people through software and web development!", "This summer, I am heading to J.P. Morgan as a Software Engineer intern!"] 
    resume = "Alan_Nguyen_Resume.pdf"

[params.process]
    enable = true
    title = "My Work"

[params.footer]
    enable = true
