baseURL = "https://alannguyen.dev/"
languageCode = "en-us"
title = "</alan nguyen>"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-145579470-1"

datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    theme_color = "tomato"
    description = "Website of Alan Nguyen"
    favicon = "favicon.png"
    logo = "logo.png"
    email = "iam@alannguyen.dev"
    linkedin = "https://www.linkedin.com/in/anguyen120/"
    github = "anguyen120"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar.jpg"
    subtitle = "Howdy! I am Alan, a student from Texas."
    hero_right = ["**I am currently a senior at Texas A&M University pursuing a Bachelor's degree in Computing.**", "I had the fantastic opportunity to go on exchange in Cyprus. During my study abroad, I collaborated with University of Cyprus' Laboratory for Internet Computing while maintaining my position as a Software Assistant. I performed analysis of fake news language evolution by applying statistical methods on the time series of fake news' linguistic cues. Besides learning Natural Language Processing, I unexpectedly picked up some Greek too!", "I am interested in an internship for summer 2021. Please don't hesitate to contact me. 👍"] 
    resume = "Alan_Nguyen_Resume.pdf"

[params.process]
    enable = true
    title = "My Work"

[params.footer]
    enable = true
